--univ.xyzmat
function c298.initial_effect(c)
	c:EnableReviveLimit()
--
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetCode(EFFECT_XYZ_LEVEL)
	e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e1:SetRange(LOCATION_MZONE)
	e1:SetValue(1)
	c:RegisterEffect(e1)
	--xyz
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_SINGLE)
	e2:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e2:SetCode(EFFECT_XYZ_LEVEL)
	e2:SetValue(2)
	e2:SetRange(LOCATION_MZONE)
	c:RegisterEffect(e2)
	--xyz
	local e3=Effect.CreateEffect(c)
	e3:SetType(EFFECT_TYPE_SINGLE)
	e3:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e3:SetCode(EFFECT_XYZ_LEVEL)
	e3:SetValue(3)
	e3:SetRange(LOCATION_MZONE)
	c:RegisterEffect(e3)
	--xyz
	local e4=Effect.CreateEffect(c)
	e4:SetType(EFFECT_TYPE_SINGLE)
	e4:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e4:SetCode(EFFECT_XYZ_LEVEL)
	e4:SetValue(4)
	e4:SetRange(LOCATION_MZONE)
	c:RegisterEffect(e4)
	--xyz
	local e5=Effect.CreateEffect(c)
	e5:SetType(EFFECT_TYPE_SINGLE)
	e5:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e5:SetCode(EFFECT_XYZ_LEVEL)
	e5:SetValue(5)
	e5:SetRange(LOCATION_MZONE)
	c:RegisterEffect(e5)
	--xyz
	local e6=Effect.CreateEffect(c)
	e6:SetType(EFFECT_TYPE_SINGLE)
	e6:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e6:SetCode(EFFECT_XYZ_LEVEL)
	e6:SetValue(6)
	e6:SetRange(LOCATION_MZONE)
	c:RegisterEffect(e6)
	--xyz
	local e7=Effect.CreateEffect(c)
	e7:SetType(EFFECT_TYPE_SINGLE)
	e7:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e7:SetCode(EFFECT_XYZ_LEVEL)
	e7:SetValue(7)
	e7:SetRange(LOCATION_MZONE)
	c:RegisterEffect(e7)
	--xyz
	local e8=Effect.CreateEffect(c)
	e8:SetType(EFFECT_TYPE_SINGLE)
	e8:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e8:SetCode(EFFECT_XYZ_LEVEL)
	e8:SetValue(8)
	e8:SetRange(LOCATION_MZONE)
	c:RegisterEffect(e8)
	--xyz
	local e9=Effect.CreateEffect(c)
	e9:SetType(EFFECT_TYPE_SINGLE)
	e9:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e9:SetCode(EFFECT_XYZ_LEVEL)
	e9:SetValue(9)
	e9:SetRange(LOCATION_MZONE)
	c:RegisterEffect(e9)
	--xyz
	local e10=Effect.CreateEffect(c)
	e10:SetType(EFFECT_TYPE_SINGLE)
	e10:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e10:SetCode(EFFECT_XYZ_LEVEL)
	e10:SetValue(10)
	e10:SetRange(LOCATION_MZONE)
	c:RegisterEffect(e10)
	--xyz
	local e11=Effect.CreateEffect(c)
	e11:SetType(EFFECT_TYPE_SINGLE)
	e11:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e11:SetCode(EFFECT_XYZ_LEVEL)
	e11:SetValue(11)
	e11:SetRange(LOCATION_MZONE)
	c:RegisterEffect(e11)
	--xyz
	local e12=Effect.CreateEffect(c)
	e12:SetType(EFFECT_TYPE_SINGLE)
	e12:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e12:SetCode(EFFECT_XYZ_LEVEL)
	e12:SetValue(12)
	e12:SetRange(LOCATION_MZONE)
	c:RegisterEffect(e12)
	--xyz
	local e13=Effect.CreateEffect(c)
	e13:SetType(EFFECT_TYPE_SINGLE)
	e13:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e13:SetCode(EFFECT_XYZ_LEVEL)
	e13:SetValue(13)
	e13:SetRange(LOCATION_MZONE)
	c:RegisterEffect(e13)
	--
	local e14=Effect.CreateEffect(c)
	e14:SetType(EFFECT_TYPE_SINGLE)
	e14:SetRange(LOCATION_MZONE)
	e14:SetCode(511001225)
	e14:SetValue(1)
	e14:SetOperation(c298.tgval)
	c:RegisterEffect(e14)
	--
	local e15=Effect.CreateEffect(c)
	e15:SetType(EFFECT_TYPE_SINGLE)
	e15:SetRange(LOCATION_MZONE)
	e15:SetCode(511001225)
	e15:SetValue(2)
	e15:SetOperation(c298.tgval)
	c:RegisterEffect(e15)
	--
	local e16=Effect.CreateEffect(c)
	e16:SetType(EFFECT_TYPE_SINGLE)
	e16:SetRange(LOCATION_MZONE)
	e16:SetCode(511001225)
	e16:SetValue(3)
	e16:SetOperation(c298.tgval)
	c:RegisterEffect(e16)
	--
	local e17=Effect.CreateEffect(c)
	e17:SetType(EFFECT_TYPE_SINGLE)
	e17:SetRange(LOCATION_MZONE)
	e17:SetCode(511001225)
	e17:SetValue(4)
	e17:SetOperation(c298.tgval)
	c:RegisterEffect(e17)
	--
	local e18=Effect.CreateEffect(c)
	e18:SetType(EFFECT_TYPE_SINGLE)
	e18:SetRange(LOCATION_MZONE)
	e18:SetCode(511001225)
	e18:SetValue(5)
	e18:SetOperation(c298.tgval)
	c:RegisterEffect(e18)
	--
	local e19=Effect.CreateEffect(c)
	e19:SetType(EFFECT_TYPE_SINGLE)
	e19:SetRange(LOCATION_MZONE)
	e19:SetCode(511001225)
	e19:SetValue(6)
	e19:SetOperation(c298.tgval)
	c:RegisterEffect(e19)
--
	local e20=Effect.CreateEffect(c)
	e20:SetDescription(aux.Stringid(298,0))
	e20:SetType(EFFECT_TYPE_IGNITION)
	e20:SetRange(LOCATION_MZONE)
	e20:SetTarget(c298.nametg)
	e20:SetOperation(c298.nameop)
	c:RegisterEffect(e20)
	--cannot special summon
	local e21=Effect.CreateEffect(c)
	e21:SetType(EFFECT_TYPE_SINGLE)
	e21:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e21:SetCode(EFFECT_SPSUMMON_CONDITION)
	e21:SetValue(aux.FALSE)
	c:RegisterEffect(e21)
	--special summon
	local e22=Effect.CreateEffect(c)
	e22:SetType(EFFECT_TYPE_FIELD)
	e22:SetCode(EFFECT_SPSUMMON_PROC)
	e22:SetProperty(EFFECT_FLAG_UNCOPYABLE)
	e22:SetRange(LOCATION_HAND)
	e22:SetCondition(c298.spcon)
	e22:SetTarget(c298.sptg)
	e22:SetOperation(c298.spop)
	c:RegisterEffect(e22)
  --effect gain
	--special summon
	local e23=Effect.CreateEffect(c)
	e23:SetType(EFFECT_TYPE_FIELD)
	e23:SetCode(EFFECT_SPSUMMON_PROC)
	e23:SetProperty(EFFECT_FLAG_UNCOPYABLE)
	e23:SetRange(LOCATION_EXTRA)
	e23:SetTarget(c298.target)
	e23:SetOperation(c298.operation)
	local e24=Effect.CreateEffect(c)
	e24:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_GRANT)
	e24:SetRange(LOCATION_MZONE)
	e24:SetTargetRange(LOCATION_EXTRA,0)
	e24:SetTarget(c298.eftg)
	e24:SetLabelObject(e23)
	c:RegisterEffect(e24)
end
function c298.eftg(e,c)
	return c:IsType(TYPE_XYZ)
end
function c298.target(e,tp,eg,ev,ep,re,r,rp,chk)
	if chk==0 then return Duel.IsExistingMatchingCard(s.filter,tp,LOCATION_MZONE,0,1,nil,e:GetHandler()) and e:GetHandler():IsCanBeSpecialSummoned(e,SUMMON_TYPE_SPECIAL,tp,true,false) end
	local tg=Duel.SelectMatchingCard(tp,s.filter,tp,LOCATION_MZONE,0,1,1,nil,e:GetHandler())
	Duel.SetTargetCard(tg)
	Duel.SetOperationInfo(0,CATEGORY_SPECIAL_SUMMON,e:GetHandler(),1,0,0)
end
function c298.operation(e,tp,eg,ev,ep,re,r,rp)
	local c=e:GetHandler()
	local tg=Duel.GetTargetCards(e)
	if c:IsCanBeSpecialSummoned(e,SUMMON_TYPE_SPECIAL,tp,true,false) and tg and #tg>0 then
		local mg=tg:Clone()
		local tc=tg:GetFirst()
		while tc do
			if tc:GetOverlayCount()~=0 then Duel.SendtoGrave(tc:GetOverlayGroup(),REASON_RULE) end
			tc=tg:GetNext()
		end
		c:SetMaterial(mg)
		Duel.Overlay(c,mg)
		Duel.SpecialSummon(c,SUMMON_TYPE_SPECIAL,tp,tp,true,false,POS_FACEUP)
	end
end
function s.filter1(c)
	return c:IsAbleToHand() and c:IsCode(78509901)
end
function c298.tgval(e,c)
	return c:IsType(TYPE_XYZ)
end
function c298.nametg(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return true end
	local ac=Duel.AnnounceCard(tp)
	Duel.SetTargetParam(ac)
	Duel.SetOperationInfo(0,CATEGORY_ANNOUNCE,nil,0,tp,ANNOUNCE_CARD_FILTER)
end
function c298.nameop(e,tp,eg,ep,ev,re,r,rp)
	local ac=Duel.GetChainInfo(0,CHAININFO_TARGET_PARAM)
	local c=e:GetHandler()
	if c:IsRelateToEffect(e) and c:IsFaceup() then
		local e1=Effect.CreateEffect(c)
		e1:SetType(EFFECT_TYPE_SINGLE)
		e1:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
		e1:SetCode(EFFECT_CHANGE_CODE)
		e1:SetValue(ac)
		e1:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_END)
		c:RegisterEffect(e1)
		local e2=Effect.CreateEffect(c)
		e2:SetType(EFFECT_TYPE_SINGLE)
		e2:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
		e2:SetCode(EFFECT_CHANGE_RACE)
		e2:SetValue(ac)
		e2:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_END)
		c:RegisterEffect(e2)
		local e3=Effect.CreateEffect(c)
		e3:SetType(EFFECT_TYPE_SINGLE)
		e3:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
		e3:SetCode(EFFECT_CHANGE_ATTRIBUTE)
		e3:SetValue(ac)
		e3:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_END)
		c:RegisterEffect(e3)
		local e4=Effect.CreateEffect(c)
		e4:SetType(EFFECT_TYPE_SINGLE)
		e4:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
		e4:SetCode(EFFECT_ADD_TYPE)
		e4:SetValue(TYPE_XYZ)
		e4:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_END)
		c:RegisterEffect(e4)
	end
end
function c298.spcon(e,c)
	if c==nil then return true end
	return Duel.CheckReleaseGroup(c:GetControler(),Card.IsType,1,false,1,true,c,c:GetControler(),nil,false,nil,TYPE_XYZ)
end
function c298.sptg(e,tp,eg,ep,ev,re,r,rp,c)
	local g=Duel.SelectReleaseGroup(tp,Card.IsType,1,1,false,true,true,c,nil,nil,false,nil,TYPE_XYZ)
	if g then
		g:KeepAlive()
		e:SetLabelObject(g)
	return true
	end
	return false
end
function c298.spop(e,tp,eg,ep,ev,re,r,rp,c)
	local g=e:GetLabelObject()
	if not g then return end
	Duel.Release(g,REASON_COST)
	g:DeleteGroup()
end
