--Blue-Eyes White Dragon (DM)
function c322.initial_effect(c)
--remove
local e2=Effect.CreateEffect(c)
e2:SetType(EFFECT_TYPE_QUICK_O)
e2:SetDescription(aux.Stringid(322,0))
e2:SetRange(LOCATION_DECK)
e2:SetCode(EVENT_FREE_CHAIN)
e2:SetTarget(c322.tg)
e2:SetOperation(c322.op)
c:RegisterEffect(e2)
end
function c322.filter(c)
	return c:IsAbleToRemove()
end
function c322.tg(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return Duel.IsExistingMatchingCard(c322.filter,tp,LOCATION_DECK+LOCATION_MZONE+LOCATION_GRAVE,0,1,nil) end
	local sg=Duel.GetMatchingGroup(c322.filter,tp,LOCATION_DECK+LOCATION_HAND+LOCATION_EXTRA,0,nil)
local e1=Effect.CreateEffect(e:GetHandler())
	e1:SetType(EFFECT_TYPE_FIELD)
	e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e1:SetTargetRange(1,0)
	e1:SetReset(RESET_CHAIN)
	e1:SetCode(EFFECT_CANNOT_LOSE_LP)
	Duel.RegisterEffect(e1,tp)
	Duel.SetOperationInfo(0,CATEGORY_REMOVE,sg,#sg,0,0)
end
function c322.op(e,tp,eg,ep,ev,re,r,rp)
	local sg=Duel.GetMatchingGroup(c322.filter,tp,LOCATION_DECK+LOCATION_HAND+LOCATION_EXTRA,0,nil)
	Duel.Remove(sg,POS_FACEDOWN,REASON_EFFECT)
	local ac=Duel.CreateToken(tp,71413901)
	local bc=Duel.CreateToken(tp,82108372)
	local cc=Duel.CreateToken(tp,39168895)
	local dc=Duel.CreateToken(tp,78636495)
	local ec=Duel.CreateToken(tp,42386471)
	local fc=Duel.CreateToken(tp,16956455)
	local gc=Duel.CreateToken(tp,85306040)
	local hc=Duel.CreateToken(tp,89222931)
	local ic=Duel.CreateToken(tp,85087012)
	local jc=Duel.CreateToken(tp,18430390)
	local kc=Duel.CreateToken(tp,61802346)
	local lc=Duel.CreateToken(tp,39303359)
	local mc=Duel.CreateToken(tp,54040221)
	local nc=Duel.CreateToken(tp,52319752)
	local oc=Duel.CreateToken(tp,14089428)
	local pc=Duel.CreateToken(tp,76203291)
	local qc=Duel.CreateToken(tp,75081613)
	local rc=Duel.CreateToken(tp,96235275)
	local sc=Duel.CreateToken(tp,41113025)
	local tc=Duel.CreateToken(tp,6061630)
	local uc=Duel.CreateToken(tp,92826944)
	local vc=Duel.CreateToken(tp,84847656)
	local wc=Duel.CreateToken(tp,74976215)
	local xc=Duel.CreateToken(tp,69695704)
	local yc=Duel.CreateToken(tp,45041488)
	local zc=Duel.CreateToken(tp,12435193)
	local ab=Duel.CreateToken(tp,80925836)
	local bb=Duel.CreateToken(tp,42463414)
	local cb=Duel.CreateToken(tp,77135531)
	local db=Duel.CreateToken(tp,10321588)
	local eb=Duel.CreateToken(tp,4694209)
	local fb=Duel.CreateToken(tp,39037517)
	local gb=Duel.CreateToken(tp,37792478)
	local hb=Duel.CreateToken(tp,49680980)
	local ib=Duel.CreateToken(tp,82199284)
	local jb=Duel.CreateToken(tp,20474741)
	local kb=Duel.CreateToken(tp,83957459)
	local lb=Duel.CreateToken(tp,66816282)
	local mb=Duel.CreateToken(tp,91438994)
	local nb=Duel.CreateToken(tp,62950604)
	local ob=Duel.CreateToken(tp,47013502)
	local pb=Duel.CreateToken(tp,85682655)
	local qb=Duel.CreateToken(tp,4611269)
	local rb=Duel.CreateToken(tp,95905259)
	local sb=Duel.CreateToken(tp,1371589)
	local tb=Duel.CreateToken(tp,66499018)
	local ub=Duel.CreateToken(tp,64892035)
	local vb=Duel.CreateToken(tp,40921545)
	local wb=Duel.CreateToken(tp,98225108)
	local xb=Duel.CreateToken(tp,42969214)
	local yb=Duel.CreateToken(tp,97396380)
	local zb=Duel.CreateToken(tp,89362180)
	local aa=Duel.CreateToken(tp,15767889)
	local ba=Duel.CreateToken(tp,50896944)
	local ca=Duel.CreateToken(tp,42364374)
	Duel.SendtoDeck(ac,nil,2,REASON_RULE)
	Duel.SendtoDeck(bc,nil,2,REASON_RULE)
	Duel.SendtoDeck(cc,nil,2,REASON_RULE)
	Duel.SendtoDeck(dc,nil,2,REASON_RULE)
	Duel.SendtoDeck(ec,nil,2,REASON_RULE)
	Duel.SendtoDeck(fc,nil,2,REASON_RULE)
	Duel.SendtoDeck(gc,nil,2,REASON_RULE)
	Duel.SendtoDeck(hc,nil,2,REASON_RULE)
	Duel.SendtoDeck(ic,nil,2,REASON_RULE)
	Duel.SendtoDeck(jc,nil,2,REASON_RULE)
	Duel.SendtoDeck(kc,nil,2,REASON_RULE)
	Duel.SendtoDeck(lc,nil,2,REASON_RULE)
	Duel.SendtoDeck(mc,nil,2,REASON_RULE)
	Duel.SendtoDeck(nc,nil,2,REASON_RULE)
	Duel.SendtoDeck(oc,nil,2,REASON_RULE)
	Duel.SendtoDeck(pc,nil,2,REASON_RULE)
	Duel.SendtoDeck(qc,nil,2,REASON_RULE)
	Duel.SendtoDeck(rc,nil,2,REASON_RULE)
	Duel.SendtoDeck(sc,nil,2,REASON_RULE)
	Duel.SendtoDeck(tc,nil,2,REASON_RULE)
	Duel.SendtoDeck(uc,nil,2,REASON_RULE)
	Duel.SendtoDeck(vc,nil,2,REASON_RULE)
	Duel.SendtoDeck(xc,nil,2,REASON_RULE)
	Duel.SendtoDeck(yc,nil,2,REASON_RULE)
	Duel.SendtoDeck(zc,nil,2,REASON_RULE)
	Duel.SendtoDeck(ab,nil,2,REASON_RULE)
	Duel.SendtoDeck(bb,nil,2,REASON_RULE)
	Duel.SendtoDeck(cb,nil,2,REASON_RULE)
	Duel.SendtoDeck(db,nil,2,REASON_RULE)
	Duel.SendtoDeck(eb,nil,2,REASON_RULE)
	Duel.SendtoDeck(fb,nil,2,REASON_RULE)
	Duel.SendtoDeck(gb,nil,2,REASON_RULE)
	Duel.SendtoDeck(hb,nil,2,REASON_RULE)
	Duel.SendtoDeck(ib,nil,2,REASON_RULE)
	Duel.SendtoDeck(jb,nil,2,REASON_RULE)
	Duel.SendtoDeck(kb,nil,2,REASON_RULE)
	Duel.SendtoDeck(lb,nil,2,REASON_RULE)
	Duel.SendtoDeck(mb,nil,2,REASON_RULE)
	Duel.SendtoDeck(nb,nil,2,REASON_RULE)
	Duel.SendtoDeck(ob,nil,2,REASON_RULE)
	Duel.SendtoDeck(pb,nil,2,REASON_RULE)
	Duel.SendtoDeck(qb,nil,2,REASON_RULE)
	Duel.SendtoDeck(rb,nil,2,REASON_RULE)
	Duel.SendtoDeck(sb,nil,2,REASON_RULE)
	Duel.SendtoDeck(tb,nil,2,REASON_RULE)
	Duel.SendtoDeck(ub,nil,2,REASON_RULE)
	Duel.SendtoDeck(vb,nil,2,REASON_RULE)
	Duel.SendtoDeck(wb,nil,2,REASON_RULE)
	Duel.SendtoDeck(xb,nil,2,REASON_RULE)
	Duel.SendtoDeck(yb,nil,2,REASON_RULE)
	Duel.SendtoDeck(zb,nil,2,REASON_RULE)
	Duel.SendtoDeck(aa,nil,2,REASON_RULE)
	Duel.SendtoDeck(ba,nil,2,REASON_RULE)
	Duel.SendtoDeck(ca,nil,2,REASON_RULE)
Duel.SetLP(tp,4000)
		Duel.ShuffleDeck(tp)
	Duel.Draw(tp,5,REASON_EFFECT)
end
