--Blue-Eyes White Dragon (DM)
function c322.initial_effect(c)
		--attack
	local e1=Effect.CreateEffect(c)
	e1:SetCategory(CATEGORY_DESTROY)
	e1:SetProperty(EFFECT_FLAG_DAMAGE_STEP+EFFECT_FLAG_DELAY)
	e1:SetDescription(aux.Stringid(322,0))
	e1:SetType(EFFECT_TYPE_QUICK_O)
	e1:SetCode(EVENT_PRE_DAMAGE_CALCULATE)
	e1:SetRange(LOCATION_EXTRA)
	e1:SetCondition(c322.dmcon)
	e1:SetTarget(c322.tg)
	e1:SetOperation(c322.op)
	e1:SetHintTiming(TIMING_DAMAGE_CAL) --credit's to keddy
	c:RegisterEffect(e1)
	--effect damage
	local e2=e1:Clone()
	e2:SetDescription(aux.Stringid(322,1))
	e2:SetCode(EVENT_CHAINING)
	e2:SetCondition(c322.edcon)
	c:RegisterEffect(e2)
--remove
local e4=Effect.CreateEffect(c)
e4:SetType(EFFECT_TYPE_QUICK_O)
e4:SetDescription(aux.Stringid(322,2))
e4:SetRange(LOCATION_EXTRA)
e4:SetCode(EVENT_FREE_CHAIN)
e4:SetCountLimit(1)
e4:SetTarget(c322.tg)
e4:SetOperation(c322.op)
c:RegisterEffect(e4)
end
function c322.dmcon(e,tp,eg,ev,ep,re,r,rp)
	local a=Duel.GetAttacker()
	local lp=Duel.GetLP(tp)
	e:SetLabelObject(a)
	return Duel.GetBattleDamage(tp)>=lp
end
function c322.filter(c)
	return c:IsAbleToRemove()
end
function c322.tg(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return Duel.IsExistingMatchingCard(c322.filter,tp,LOCATION_DECK+LOCATION_MZONE+LOCATION_GRAVE,0,1,nil) end
	local sg=Duel.GetMatchingGroup(c322.filter,tp,LOCATION_DECK+LOCATION_HAND+LOCATION_EXTRA,0,nil)
local e1=Effect.CreateEffect(e:GetHandler())
	e1:SetType(EFFECT_TYPE_FIELD)
	e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e1:SetTargetRange(1,0)
	e1:SetReset(RESET_CHAIN)
	e1:SetCode(EFFECT_CANNOT_LOSE_LP)
	Duel.RegisterEffect(e1,tp)
	local e0=Effect.CreateEffect(e:GetHandler())
	e0:SetType(EFFECT_TYPE_FIELD)
	e0:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e0:SetCode(EFFECT_CANNOT_ACTIVATE)
	e0:SetTargetRange(1,1)
	e0:SetValue(1)
	e0:SetReset(RESET_PHASE+PHASE_END)
	Duel.RegisterEffect(e0,tp)
	--skip phases until Battle Phase
	local p=Duel.GetTurnPlayer()
	Duel.SkipPhase(p,PHASE_DRAW,RESET_PHASE+PHASE_END,1)
	Duel.SkipPhase(p,PHASE_STANDBY,RESET_PHASE+PHASE_END,1)
	Duel.SkipPhase(p,PHASE_MAIN1,RESET_PHASE+PHASE_END,1)
	Duel.SkipPhase(p,PHASE_BATTLE,RESET_PHASE+PHASE_END,1)
	Duel.SkipPhase(p,PHASE_MAIN2,RESET_PHASE+PHASE_END,1)
	Duel.SkipPhase(p,PHASE_END,RESET_PHASE+PHASE_END,1)
	Duel.SetOperationInfo(0,CATEGORY_REMOVE,sg,#sg,0,0)
end
function c322.op(e,tp,eg,ep,ev,re,r,rp)
	local sg=Duel.GetMatchingGroup(c322.filter,tp,LOCATION_ALL,0,nil)
	Duel.SendtoDeck(sg,nil,-2,REASON_RULE)
	local e1=Effect.CreateEffect(e:GetHandler())
	e1:SetType(EFFECT_TYPE_FIELD)
	e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e1:SetCode(EFFECT_SKIP_TURN)
	e1:SetTargetRange(0,1)
	e1:SetReset(RESET_PHASE+PHASE_END+RESET_OPPO_TURN)
	Duel.RegisterEffect(e1,tp)
	local ac=Duel.CreateToken(tp,52339733)
	local bc=Duel.CreateToken(tp,67249508)
	local cc=Duel.CreateToken(tp,57831349)
	local dc=Duel.CreateToken(tp,57831349)
	local ec=Duel.CreateToken(tp,77783947)
	local fc=Duel.CreateToken(tp,77783947)
	local gc=Duel.CreateToken(tp,39122311)
	local hc=Duel.CreateToken(tp,30398342)
	local ic=Duel.CreateToken(tp,30398342)
	local jc=Duel.CreateToken(tp,99788587)
	local kc=Duel.CreateToken(tp,98239899)
	local lc=Duel.CreateToken(tp,96355986)
	local mc=Duel.CreateToken(tp,94156050)
	local nc=Duel.CreateToken(tp,67249508)
	local oc=Duel.CreateToken(tp,67249508)
	local pc=Duel.CreateToken(tp,23068051)
	local qc=Duel.CreateToken(tp,14821890)
	local rc=Duel.CreateToken(tp,43912676)
	local sc=Duel.CreateToken(tp,83746708)
	local tc=Duel.CreateToken(tp,43577607)
	local uc=Duel.CreateToken(tp,43577607)
	local vc=Duel.CreateToken(tp,237)
	local wc=Duel.CreateToken(tp,511001126)
	local xc=Duel.CreateToken(tp,511000613)
	local yc=Duel.CreateToken(tp,83764719)
	local zc=Duel.CreateToken(tp,72302403)
	local ab=Duel.CreateToken(tp,55144522)
	local bb=Duel.CreateToken(tp,17183908)
	local cb=Duel.CreateToken(tp,17183908)
	local db=Duel.CreateToken(tp,61488417)
	local eb=Duel.CreateToken(tp,61488417)
	local fb=Duel.CreateToken(tp,61488417)
	local gb=Duel.CreateToken(tp,35089369)
	local hb=Duel.CreateToken(tp,35089369)
	local ib=Duel.CreateToken(tp,25935625)
	local jb=Duel.CreateToken(tp,25935625)
	local kb=Duel.CreateToken(tp,25935625)
	local lb=Duel.CreateToken(tp,2095764)
	local mb=Duel.CreateToken(tp,2095764)
	local nb=Duel.CreateToken(tp,24218047)
	local ob=Duel.CreateToken(tp,21495657)
	local pb=Duel.CreateToken(tp,21495657)
	local qb=Duel.CreateToken(tp,66500065)
	local rb=Duel.CreateToken(tp,95833645)
	local sb=Duel.CreateToken(tp,88724332)
	local tb=Duel.CreateToken(tp,56495147)
	local ub=Duel.CreateToken(tp,56495147)
	local vb=Duel.CreateToken(tp,30106950)
	local wb=Duel.CreateToken(tp,99946920)
	local xb=Duel.CreateToken(tp,99946920)
	local yb=Duel.CreateToken(tp,58990362)
	local zb=Duel.CreateToken(tp,58990362)
	local aa=Duel.CreateToken(tp,93490856)
	local ba=Duel.CreateToken(tp,92723496)
	local ca=Duel.CreateToken(tp,82321037)
	local da=Duel.CreateToken(tp,30539496)
	local ea=Duel.CreateToken(tp,94160895)
	local fa=Duel.CreateToken(tp,96746083)
	local ga=Duel.CreateToken(tp,96746083)
	local ha=Duel.CreateToken(tp,96746083)
	local ia=Duel.CreateToken(tp,9999996)
	local ja=Duel.CreateToken(tp,21123811)
	local ka=Duel.CreateToken(tp,35952884)
	local la=Duel.CreateToken(tp,19048328)
	local ma=Duel.CreateToken(tp,83755611)
	local na=Duel.CreateToken(tp,43202238)
	local oa=Duel.CreateToken(tp,36898537)
	local pa=Duel.CreateToken(tp,53714009)
	local qa=Duel.CreateToken(tp,511001517)
	local ra=Duel.CreateToken(tp,65536818)
	local sa=Duel.CreateToken(tp,65536818)
	local ta=Duel.CreateToken(tp,55863245)
	local ua=Duel.CreateToken(tp,15240238)
	local va=Duel.CreateToken(tp,511000798)
	local wa=Duel.CreateToken(tp,88581108)
	local xa=Duel.CreateToken(tp,210777231)
	local ya=Duel.CreateToken(tp,96633955)
	local za=Duel.CreateToken(tp,47710198)
	local aaa=Duel.CreateToken(tp,69248256)
	local baa=Duel.CreateToken(tp,202114502)
	local caa=Duel.CreateToken(tp,66500065)
	Duel.SendtoDeck(ac,nil,2,REASON_RULE)
	Duel.SendtoDeck(bc,nil,2,REASON_RULE)
	Duel.SendtoDeck(cc,nil,2,REASON_RULE)
	Duel.SendtoDeck(dc,nil,2,REASON_RULE)
	Duel.SendtoDeck(ec,nil,2,REASON_RULE)
	Duel.SendtoDeck(fc,nil,2,REASON_RULE)
	Duel.SendtoDeck(gc,nil,2,REASON_RULE)
	Duel.SendtoDeck(hc,nil,2,REASON_RULE)
	Duel.SendtoDeck(ic,nil,2,REASON_RULE)
	Duel.SendtoDeck(jc,nil,2,REASON_RULE)
	Duel.SendtoDeck(kc,nil,2,REASON_RULE)
	Duel.SendtoDeck(lc,nil,2,REASON_RULE)
	Duel.SendtoDeck(mc,nil,2,REASON_RULE)
	Duel.SendtoDeck(nc,nil,2,REASON_RULE)
	Duel.SendtoDeck(oc,nil,2,REASON_RULE)
	Duel.SendtoDeck(pc,nil,2,REASON_RULE)
	Duel.SendtoDeck(qc,nil,2,REASON_RULE)
	Duel.SendtoDeck(rc,nil,2,REASON_RULE)
	Duel.SendtoDeck(sc,nil,2,REASON_RULE)
	Duel.SendtoDeck(tc,nil,2,REASON_RULE)
	Duel.SendtoDeck(uc,nil,2,REASON_RULE)
	Duel.SendtoDeck(vc,nil,2,REASON_RULE)
	Duel.SendtoDeck(xc,nil,2,REASON_RULE)
	Duel.SendtoDeck(yc,nil,2,REASON_RULE)
	Duel.SendtoDeck(zc,nil,2,REASON_RULE)
	Duel.SendtoDeck(ab,nil,2,REASON_RULE)
	Duel.SendtoDeck(bb,nil,2,REASON_RULE)
	Duel.SendtoDeck(cb,nil,2,REASON_RULE)
	Duel.SendtoDeck(db,nil,2,REASON_RULE)
	Duel.SendtoDeck(eb,nil,2,REASON_RULE)
	Duel.SendtoDeck(fb,nil,2,REASON_RULE)
	Duel.SendtoDeck(gb,nil,2,REASON_RULE)
	Duel.SendtoDeck(hb,nil,2,REASON_RULE)
	Duel.SendtoDeck(ib,nil,2,REASON_RULE)
	Duel.SendtoDeck(jb,nil,2,REASON_RULE)
	Duel.SendtoDeck(kb,nil,2,REASON_RULE)
	Duel.SendtoDeck(lb,nil,2,REASON_RULE)
	Duel.SendtoDeck(mb,nil,2,REASON_RULE)
	Duel.SendtoDeck(nb,nil,2,REASON_RULE)
	Duel.SendtoDeck(ob,nil,2,REASON_RULE)
	Duel.SendtoDeck(pb,nil,2,REASON_RULE)
	Duel.SendtoDeck(qb,nil,2,REASON_RULE)
	Duel.SendtoDeck(rb,nil,2,REASON_RULE)
	Duel.SendtoDeck(sb,nil,2,REASON_RULE)
	Duel.SendtoDeck(tb,nil,2,REASON_RULE)
	Duel.SendtoDeck(ub,nil,2,REASON_RULE)
	Duel.SendtoDeck(vb,nil,2,REASON_RULE)
	Duel.SendtoDeck(wb,nil,2,REASON_RULE)
	Duel.SendtoDeck(xb,nil,2,REASON_RULE)
	Duel.SendtoDeck(yb,nil,2,REASON_RULE)
	Duel.SendtoDeck(zb,nil,2,REASON_RULE)
	Duel.SendtoDeck(aa,nil,2,REASON_RULE)
	Duel.SendtoDeck(ba,nil,2,REASON_RULE)
	Duel.SendtoDeck(ca,nil,2,REASON_RULE)
	Duel.SendtoDeck(da,nil,2,REASON_RULE)
	Duel.SendtoDeck(ea,nil,2,REASON_RULE) 
	Duel.SendtoDeck(fa,nil,2,REASON_RULE)
	Duel.SendtoDeck(ga,nil,2,REASON_RULE)
	Duel.SendtoDeck(ha,nil,2,REASON_RULE)
	Duel.SendtoDeck(ia,nil,2,REASON_RULE)
	Duel.SendtoDeck(ja,nil,2,REASON_RULE)
	Duel.SendtoDeck(ka,nil,2,REASON_RULE)
	Duel.SendtoDeck(la,nil,2,REASON_RULE)
	Duel.SendtoDeck(ma,nil,2,REASON_RULE)
	Duel.SendtoDeck(na,nil,2,REASON_RULE)
	Duel.SendtoDeck(oa,nil,2,REASON_RULE)
	Duel.SendtoDeck(pa,nil,2,REASON_RULE)
	Duel.SendtoDeck(qa,nil,2,REASON_RULE)
	Duel.SendtoDeck(ra,nil,2,REASON_RULE)
	Duel.SendtoDeck(sa,nil,2,REASON_RULE)
	Duel.SendtoDeck(ta,nil,2,REASON_RULE)
	Duel.SendtoDeck(ua,nil,2,REASON_RULE)
	Duel.SendtoDeck(va,nil,2,REASON_RULE)
	Duel.SendtoDeck(wa,nil,2,REASON_RULE)
	Duel.SendtoDeck(xa,nil,2,REASON_RULE)
	Duel.SendtoDeck(ya,nil,2,REASON_RULE)
	Duel.SendtoDeck(za,nil,2,REASON_RULE)
	Duel.SendtoDeck(aaa,nil,2,REASON_RULE)
	Duel.SendtoDeck(baa,nil,2,REASON_RULE)
	Duel.SendtoDeck(caa,nil,2,REASON_RULE)
Duel.SetLP(tp,8000)
		Duel.ShuffleDeck(tp)
	Duel.Draw(tp,5,REASON_EFFECT)
	local e2=Effect.CreateEffect(e:GetHandler())
	e2:SetType(EFFECT_TYPE_FIELD)
	e2:SetCode(EFFECT_AVOID_BATTLE_DAMAGE)
	e2:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e2:SetTargetRange(1,0)
	e2:SetValue(1)
	e2:SetReset(RESET_PHASE+PHASE_END)
	Duel.RegisterEffect(e2,tp)
	local e3=Effect.CreateEffect(e:GetHandler())
	e3:SetType(EFFECT_TYPE_FIELD)
	e3:SetCode(EFFECT_CHANGE_DAMAGE)
	e3:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e3:SetTargetRange(1,0)
	e3:SetValue(c322.damval)
	e3:SetReset(RESET_PHASE+PHASE_END)
	Duel.RegisterEffect(e3,tp)
end
function c322.damval(e,re,val,r,rp,rc)
	if bit.band(r,REASON_EFFECT)~=0 then return 0
	else return val end
end
function c322.edcon(e,tp,eg,ev,ep,re,r,rp)
	local e1=Duel.IsPlayerAffectedByEffect(tp,EFFECT_REVERSE_DAMAGE)
	local e2=Duel.IsPlayerAffectedByEffect(tp,EFFECT_REVERSE_RECOVER)
	local rd=e1 and not e2
	local rr=not e1 and e2
	local ex,cg,ct,cp,cv=Duel.GetOperationInfo(ev,CATEGORY_DAMAGE)
	if ex and (cp==tp or cp==PLAYER_ALL) and not rd 
		and not Duel.IsPlayerAffectedByEffect(tp,EFFECT_NO_EFFECT_DAMAGE) and Duel.GetLP(tp)<=cv then 
		return true 
	end
	ex,cg,ct,cp,cv=Duel.GetOperationInfo(ev,CATEGORY_RECOVER)
	return ex and (cp==tp or cp==PLAYER_ALL) and rr 
		and not Duel.IsPlayerAffectedByEffect(tp,EFFECT_NO_EFFECT_DAMAGE) and Duel.GetLP(tp)<=cv
end
function c322.edtg(e,tp,eg,ev,ep,re,r,rp,chk)
	if chk==0 then return true end
	local e1=Effect.CreateEffect(e:GetHandler())
	e1:SetType(EFFECT_TYPE_FIELD)
	e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e1:SetTargetRange(1,0)
	e1:SetReset(RESET_CHAIN)
	e1:SetCode(EFFECT_CANNOT_LOSE_LP)
	Duel.RegisterEffect(e1,tp)
		Duel.SetOperationInfo(0,CATEGORY_DESTROY,eg,1,0,0)
end
