--フォース
local s,id=GetID()
function s.initial_effect(c)
	--Activate
	local e1=Effect.CreateEffect(c)
	e1:SetProperty(EFFECT_FLAG_CARD_TARGET)
	e1:SetType(EFFECT_TYPE_ACTIVATE)
	e1:SetCode(EVENT_FREE_CHAIN)
	e1:SetTarget(s.target)
	e1:SetOperation(s.activate)
	c:RegisterEffect(e1)
end
function s.filter(c)
	return c:IsFaceup()
end
function s.xyzfilter(c,tp)
	return c:IsFaceup() and Duel.IsExistingMatchingCard(s.filter,tp,LOCATION_MZONE,LOCATION_MZONE,1,c)
end
function s.target(e,tp,eg,ep,ev,re,r,rp,chk,chkc)
	if chkc then return chkc:IsLocation(LOCATION_MZONE) and chkc:IsControler(tp) and s.xyzfilter(chkc,tp) end
	if chk==0 then return Duel.IsExistingTarget(s.xyzfilter,tp,LOCATION_MZONE,0,1,nil,tp) end
	Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_TARGET)
	Duel.SelectTarget(tp,s.xyzfilter,tp,LOCATION_MZONE,0,1,1,nil,tp)
end
function s.activate(e,tp,eg,ep,ev,re,r,rp)
	if not e:GetHandler():IsRelateToEffect(e) then return end
	local tc=Duel.GetFirstTarget()
	if tc and tc:IsRelateToEffect(e) and tc:IsFaceup() then
		Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_FACEUP)
		local tc3=Duel.SelectMatchingCard(tp,s.filter,tp,LOCATION_MZONE,LOCATION_MZONE,1,1,tc):GetFirst()
		tc:RegisterFlagEffect(id,RESET_EVENT+RESETS_STANDARD,0,0)
		tc3:RegisterFlagEffect(id,RESET_EVENT+RESETS_STANDARD,0,0)
		--local sc=tc2:Select(tp,1,1,nil)
		--local tc3=tc2:GetFirst()
		local e1=Effect.CreateEffect(e:GetHandler())
		e1:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
		e1:SetCode(EFFECT_CHANGE_LEVEL)
		e1:SetTargetRange(1,1)
		e1:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_END)
		e1:SetLabel(TYPE_SYNCHRO)
		e1:SetLabelObject(tc)
		e1:SetTarget(s.con)
		e1:SetValue(4)
		Duel.RegisterEffect(e1,tp)
		local e2=Effect.CreateEffect(e:GetHandler())
		e2:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
		e2:SetCode(EFFECT_SYNCHRO_LEVEL)
		e2:SetTargetRange(1,1)
		e2:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_END)
		e2:SetLabel(TYPE_SYNCHRO)
		e2:SetLabelObject(tc)
		e2:SetTarget(s.con) 
		e2:SetValue(s.synval)
		Duel.RegisterEffect(e2,tp)
		local e3=Effect.CreateEffect(e:GetHandler())
		e3:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
		e3:SetCode(EFFECT_RANK_LEVEL)
		e3:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_END)
		e3:SetTargetRange(1,1)
		e3:SetLabel(TYPE_XYZ)
		e3:SetLabelObject(tc)
		e3:SetTarget(s.con)
		Duel.RegisterEffect(e3,tp)
		local e12=Effect.CreateEffect(e:GetHandler())
		e12:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
		e12:SetCode(EFFECT_CHANGE_LEVEL_FINAL)
		e12:SetTargetRange(1,1)
		e12:SetLabel(TYPE_XYZ)
		e12:SetLabelObject(tc)
		e12:SetTarget(s.con)
		e12:SetValue(7)
		e12:SetReset(RESET_EVENT+RESETS_STANDARD)
		Duel.RegisterEffect(e12,tp)
		local e4=Effect.CreateEffect(e:GetHandler())
		e4:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
		e4:SetCode(EFFECT_CHANGE_LEVEL)
		e4:SetTargetRange(1,1)
		e4:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_END)
		e4:SetLabel(TYPE_FUSION)
		e4:SetLabelObject(tc)
		e4:SetTarget(s.con)
		e4:SetValue(8)
		Duel.RegisterEffect(e4,tp)
		local e5=Effect.CreateEffect(e:GetHandler())
		e5:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
		e5:SetCode(EFFECT_ADD_TYPE)
		e5:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_END)
		e5:SetLabel(TYPE_FUSION)
		e5:SetTargetRange(1,1)
		e5:SetLabelObject(tc)
		e5:SetTarget(s.con)
		e5:SetValue(TYPE_TUNER)
		Duel.RegisterEffect(e5,tp)
		--if tc3 and tc3:IsRelateToEffect(e) and tc3:IsFaceup() then
		--Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_FACEUP)
		local e6=Effect.CreateEffect(e:GetHandler())
		e6:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
		e6:SetCode(EFFECT_CHANGE_LEVEL)
		e6:SetTargetRange(1,1)
		e6:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_END)
		e6:SetLabel(TYPE_SYNCHRO)
		e6:SetLabelObject(tc3)
		e6:SetTarget(s.con)
		e6:SetValue(4)
		Duel.RegisterEffect(e6,tp)
		local e7=Effect.CreateEffect(e:GetHandler())
		e7:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
		e7:SetCode(EFFECT_SYNCHRO_LEVEL)
		e7:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_END)
		e7:SetTargetRange(1,1)
		e7:SetLabel(TYPE_SYNCHRO)
		e7:SetLabelObject(tc3)
		e7:SetTarget(s.con) 
		e7:SetValue(s.synval)
		Duel.RegisterEffect(e7,tp)
		local e8=Effect.CreateEffect(e:GetHandler())
		e8:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
		e8:SetCode(EFFECT_RANK_LEVEL)
		e8:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_END)
		e8:SetLabel(TYPE_XYZ)
		e8:SetTargetRange(1,1)
		e8:SetLabelObject(tc3)
		e8:SetTarget(s.con)
		Duel.RegisterEffect(e8,tp)
		local e11=Effect.CreateEffect(e:GetHandler())
		e11:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
		e11:SetCode(EFFECT_CHANGE_LEVEL_FINAL)
		e11:SetLabel(TYPE_XYZ)
		e11:SetTargetRange(1,1)
		e11:SetLabelObject(tc3)
		e11:SetTarget(s.con)
		e11:SetValue(7)
		e11:SetReset(RESET_EVENT+RESETS_STANDARD)
		Duel.RegisterEffect(e11,tp)
		local e9=Effect.CreateEffect(e:GetHandler())
		e9:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
		e9:SetCode(EFFECT_CHANGE_LEVEL)
		e9:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_END)
		e9:SetLabel(TYPE_FUSION)
		e9:SetTargetRange(1,1)
		e9:SetLabelObject(tc3)
		e9:SetTarget(s.con)
		e9:SetValue(8)
		Duel.RegisterEffect(e9,tp)
		local e10=Effect.CreateEffect(e:GetHandler())
		e10:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
		e10:SetCode(EFFECT_ADD_TYPE)
		e10:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_END)
		e10:SetLabel(TYPE_FUSION)
		e10:SetTargetRange(1,1)
		e10:SetLabelObject(tc3)
		e10:SetTarget(s.con)
		e10:SetValue(TYPE_TUNER)
		Duel.RegisterEffect(e10,tp)
	end
end
function s.synval(e,c)
	local lv=e:GetHandler():GetLevel()
	return 2*65536+lv
end
function s.con(e,c)
	return e:GetLabelObject():GetFlagEffect(id)==0 and c:IsType(e:GetLabel())
end
