--
local s,id=GetID()
function s.initial_effect(c)
	--Activate
	local e0=Effect.CreateEffect(c)
	e0:SetCategory(CATEGORY_POSITION)
	e0:SetType(EFFECT_TYPE_ACTIVATE)
	e0:SetCode(EVENT_FREE_CHAIN)
	e0:SetTarget(s.target)
	e0:SetOperation(s.activate)
	c:RegisterEffect(e0)
	--LIGHT: Play with your hand revealed
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_FIELD)
	e1:SetCode(EFFECT_CANNOT_ATTACK_ANNOUNCE)
	e1:SetRange(LOCATION_SZONE)
	e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e1:SetTargetRange(1,0)
	e1:SetTarget(s.PlayerIsAffectedByClearWorld)
	c:RegisterEffect(e1)
	local e2=e1:Clone()
	e2:SetCondition(function(e) return s.PlayerIsAffectedByClearWorld(e,1-e:GetHandlerPlayer(),ATTRIBUTE_DARK) end)
	e2:SetTargetRange(0,1)
	c:RegisterEffect(e2)
	--DARK: Monsters you control cannot declare an attack
	local e2a=Effect.CreateEffect(c)
	e2a:SetType(EFFECT_TYPE_FIELD)
	e2a:SetCode(EFFECT_CANNOT_ATTACK_ANNOUNCE)
	e2a:SetRange(LOCATION_SZONE)
	e2a:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e2a:SetTargetRange(1,0)
	e2a:SetCondition(function(e) return s.PlayerIsAffectedByClearWorld(e,e:GetHandlerPlayer(),ATTRIBUTE_DARK) end)
	c:RegisterEffect(e2a)
	local e2b=e2a:Clone()
	e2b:SetCondition(function(e) return s.PlayerIsAffectedByClearWorld(e,1-e:GetHandlerPlayer(),ATTRIBUTE_DARK) end)
	e2b:SetTargetRange(0,1)
	c:RegisterEffect(e2b)
	--EARTH: Once per turn, during your turn: Destroy 1 monster you control
	local e3a=Effect.CreateEffect(c)
	e3a:SetType(EFFECT_TYPE_FIELD)
	e3a:SetCode(EFFECT_SET_BASE_ATTACK)
	e3a:SetRange(LOCATION_SZONE)
	e3a:SetProperty(EFFECT_FLAG_DELAY)
	e3a:SetTargetRange(LOCATION_MZONE,0)
	e3a:SetCondition(function(e,tp) return s.PlayerControlsAttributeOrIsAffectedByClearWall(e,tp,ATTRIBUTE_EARTH+ATTRIBUTE_WIND) end)
	e3a:SetValue(s.atkval)
	c:RegisterEffect(e3a)
	local e3b=e3a:Clone()
	e3b:SetCode(EFFECT_SET_BASE_DEFENSE)
	e3b:SetValue(s.defval)
	c:RegisterEffect(e3b)
	local e3c=e3a:Clone()
	e3c:SetCode(EFFECT_SET_BASE_ATTACK)
	e3c:SetTargetRange(0,LOCATION_MZONE)
	e3c:SetCondition(function(e) return s.PlayerIsAffectedByClearWorld(e,1-e:GetHandlerPlayer(),ATTRIBUTE_EARTH+ATTRIBUTE_WIND) end)
	e3c:SetValue(s.atkval)
	c:RegisterEffect(e3c)
	local e3d=e3a:Clone()
	e3d:SetCode(EFFECT_SET_BASE_DEFENSE)
	e3d:SetTargetRange(0,LOCATION_MZONE)
	e3d:SetCondition(function(e) return s.PlayerIsAffectedByClearWorld(e,1-e:GetHandlerPlayer(),ATTRIBUTE_EARTH+ATTRIBUTE_WIND) end)
	e3d:SetValue(s.defval)
	c:RegisterEffect(e3d)
	--WATER: Once per turn, during your End Phase: Discard 1 card
	--activate cost
	local e4=Effect.CreateEffect(c)
	e4:SetType(EFFECT_TYPE_FIELD)
	e4:SetCode(EFFECT_ACTIVATE_COST)
	e4:SetRange(LOCATION_SZONE)
	e4:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e4:SetTargetRange(1,0)
	e4:SetCondition(function(e,tp) return s.PlayerControlsAttributeOrIsAffectedByClearWall(e,tp,ATTRIBUTE_WATER+ATTRIBUTE_FIRE) end)
	e4:SetCost(s.costchk)
	e4:SetOperation(s.costop)
	c:RegisterEffect(e4)
	local e5=e4:Clone()
	e5:SetCondition(function(e) return s.PlayerIsAffectedByClearWorld(e,1-e:GetHandlerPlayer(),ATTRIBUTE_WATER+ATTRIBUTE_FIRE) end)
	e5:SetTargetRange(0,1)
	c:RegisterEffect(e5)
	--Halve damage
	local e6=Effect.CreateEffect(c)
	e6:SetType(EFFECT_TYPE_FIELD)
	e6:SetRange(LOCATION_SZONE)
	e6:SetCode(EFFECT_CHANGE_DAMAGE)
	e6:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e6:SetCondition(function(e) return s.PlayerIsAffectedByClearWorld(e,1-e:GetHandlerPlayer(),ATTRIBUTE_DIVINE) or not s.PlayerIsAffectedByClearWorld(1-e:GetHandlerPlayer(),ATTRIBUTE_ALL-ATTRIBUTE_DIVINE) end)
	e6:SetTargetRange(1,0)
	e6:SetValue(s.val)
	c:RegisterEffect(e6)
	local e6a=e6:Clone()
	e6a:SetCondition(function(e) return s.PlayerControlsAttributeOrIsAffectedByClearWall(e,tp,ATTRIBUTE_DIVINE) or not s.PlayerControlsAttributeOrIsAffectedByClearWall(tp,ATTRIBUTE_ALL-ATTRIBUTE_DIVINE) end)
	e6a:SetTargetRange(0,1)
	c:RegisterEffect(e6a)
	--remain field
	local e7=Effect.CreateEffect(c)
	e7:SetType(EFFECT_TYPE_SINGLE)
	e7:SetCode(EFFECT_REMAIN_FIELD)
	c:RegisterEffect(e7)
end
function s.target(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return e:IsHasType(EFFECT_TYPE_ACTIVATE) end
	local c=e:GetHandler()
	c:SetTurnCounter(0)
	local sg=Duel.GetMatchingGroup(Card.IsFacedown,tp,0,LOCATION_MZONE,nil)
	Duel.SetOperationInfo(0,CATEGORY_POSITION,sg,#sg,0,0)
	--destroy
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	e1:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
	e1:SetCode(EVENT_PHASE+PHASE_END)
	e1:SetCountLimit(1)
	e1:SetRange(LOCATION_SZONE)
	e1:SetCondition(s.descon)
	e1:SetOperation(s.desop)
	e1:SetReset(RESETS_STANDARD_PHASE_END|RESET_OPPO_TURN,3)
	c:RegisterEffect(e1)
	local e3=Effect.CreateEffect(c)
	e3:SetType(EFFECT_TYPE_SINGLE)
	e3:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE+EFFECT_FLAG_IGNORE_IMMUNE+EFFECT_FLAG_SET_AVAILABLE)
	e3:SetCode(1082946)
	e3:SetLabelObject(e1)
	e3:SetOwnerPlayer(tp)
	e3:SetOperation(s.reset)
	e3:SetReset(RESETS_STANDARD_PHASE_END|RESET_OPPO_TURN,3)
	c:RegisterEffect(e3)
end
function s.reset(e,tp,eg,ep,ev,re,r,rp)
	s.desop(e:GetLabelObject(),tp,eg,ep,ev,e,r,rp)
end
function s.activate(e,tp,eg,ep,ev,re,r,rp)
	local sg=Duel.GetMatchingGroup(Card.IsFacedown,tp,0,LOCATION_MZONE,nil)
	if #sg>0 then
		Duel.ChangePosition(sg,POS_FACEUP_ATTACK,POS_FACEUP_ATTACK,POS_FACEUP_DEFENSE,POS_FACEUP_DEFENSE)
	end
end
function s.descon(e,tp,eg,ep,ev,re,r,rp)
	return Duel.IsTurnPlayer(1-tp)
end
function s.desop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local ct=c:GetTurnCounter()
	ct=ct+1
	c:SetTurnCounter(ct)
	if ct==3 then
		Duel.Destroy(c,REASON_RULE)
		if re then re:Reset() end
	end
end
function s.atkval(e,c)
	return math.ceil(c:GetAttack()/2)
end
function s.defval(e,c)
	return math.ceil(c:GetDefense()/2)
end
function s.costchk(e,te_or_c,tp)
	local ct=#{Duel.GetPlayerEffect(tp,id)}
	return Duel.CheckLPCost(tp,ct*500)
end
function s.costop(e,tp,eg,ep,ev,re,r,rp)
	Duel.PayLPCost(tp,500)
end
function s.PlayerControlsAttributeOrIsAffectedByClearWall(e,tp,eg,ep,ev,re,r,rp)
	return Duel.IsExistingMatchingCard(aux.FaceupFilter(Card.IsAttribute,ATTRIBUTE_LIGHT),e:GetHandlerPlayer(),LOCATION_MZONE,0,1,nil)
end
function s.PlayerIsAffectedByClearWorld(e,player,attribute)
	return --s.PlayerControlsAttributeOrIsAffectedByClearWall(player,attribute)
end
function s.val(e,re,dam,r,rp,rc)
	return math.floor(dam/2)
end
